apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cloudcat-meow/bdd-spring-1557159511:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cloudcat-meow/bdd-spring-1557159511:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-spring-1557159511
        chartPath: charts/bdd-spring-1557159511
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cloudcat-meow/bdd-spring-1557159511'
          image.tag: '{{.DIGEST_HEX}}'
